---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.7
    path: "/data/unifi-config"
