---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  metadata: unifi
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: unifi-config
