---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller
  namespace: monitoring
spec:
  endpoints:
    - interval: 3s
      path: /metrics
      targetPort: metrics
  namespaceSelector:
    matchNames:
    - unifi
    - monitoring
  selector:
    matchLabels:
      name: controller
