---
ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - home-assistant.private.channings.me
  tls:
    - secretName: home-assistant-tls
      hosts:
        - home-assistant.private.channings.me
hostNetwork: true
