---
kubernetes-ingress:
  controller:
    ingressClass: internal
    defaultTLSSecret:
      enabled: true
      secret: haproxy-ingress/haproxy-default-tls
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.200"
    publishService:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: amd64
  defaultBackend:
    replicaCount: 1
    nodeSelector:
      kubernetes.io/arch: amd64
