---
kubernetes-ingress:
  controller:
    kind: DaemonSet
    replicaCount: 3
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 0
      path: /healthz
      periodSeconds: 15
      port: 1042
      scheme: HTTP
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 0
      path: /healthz
      periodSeconds: 15
      port: 1042
      scheme: HTTP
      successThreshold: 1
      timeoutSeconds: 1
    ingressClass: haproxy-private
    defaultTLSSecret:
      enabled: true
      secret: null
    # nodeSelector:
    #   kubernetes.io/arch: amd64
    service:
      type: NodePort
    daemonset:
      useHostPort: false
      hostPorts:
        http: 80
        https: 443
        stat: 1024
  defaultBackend:
    replicaCount: 1
    nodeSelector:
      kubernetes.io/arch: amd64
