---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
spec:
  destination:
    namespace: haproxy-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/infrastructure/haproxy-ingress
    repoURL: 'git@github.com:LukeChannings/k8s-at-home.git'
    targetRevision: HEAD
  project: infrastructure
