---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Critical applications upon which all other apps in the cluster depend
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc
    - namespace: haproxy-ingress
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: prometheus
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
