---
name: Lint

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck yamllint
      - name: Lint
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/lint.sh"
          $GITHUB_WORKSPACE/scripts/lint.sh
